const images = {
  blueClearBtn: require('./images/btnClear.png'),
  blueDarkBtn: require('./images/btnDark.png'),
  blueLightBtn: require('./images/btnLight.png'),
  blueMediumBtn: require('./images/btnMedium.png'),
  sun: require('./images/sun.png'),
  landscape: require('./images/landscape.png'),
  sunGlasses: require('./images/sun-glasses.png'),
  highTemperature: require('./images/high-temperature.png'),
  clock: require('./images/clock.png'),
  cloud: require('./images/cloud.png'),
  angle: require('./images/angle.png'),
  exercise: require('./images/exercise.png'),
  override: require('./images/override.png'),
  control: require('./images/control.png'),
  calendar: require('./images/calendar.png'),
  check: require('./images/check.png'),
  viewLogo: require('./images/logo-view-logo.png'),
  vbgNature: require('./images/vbg-nature.png'),
  tabIcon1: require('./tabIcon1.png'),
  tabIcon2: require('./tabIcon2.png'),
  tabIcon3: require('./tabIcon3.png'),
  tabIcon4: require('./tabIcon4.png'),
  contacts: require('./images/contact.png'),
  logout: require('./images/logout.png'),
  appearance: require('./images/Appearance.png'),
  manage: require('./images/Manage.png'),
  help: require('./images/Help.png'),
  privacy: require('./images/Privacy.png'),
  intelligence: require('./images/Intelligence.png'),
  notification: require('./images/Notification.png'),
  backIcon: require('./images/backIcon.png'),
  newUser: require('./images/newUser.png'),
  userDetailsChecked: require('./images/userDetailsChecked.png'),
  editUser: require('./images/editUser.png'),
  contactBlue: require('./images/contactBlue.png'),
};
export default images;
